Homework02
Sofshik/cs102 pull request #2
Opened 2020-10-29 12:54 UTC by Sofshik

2020-10-29 19:24 UTC, anastasiiaCher commented
1. В функциях `group()`, `get_col()`, `get_block()` используйте списковые включения вместо простых циклов (если замена возможна в других функциях - тоже сделайте).
2. Воздержитесь от введения переменных, использующихся в коде всего один раз. Лучше использовать выражение, которое они заменяют.
3. Проверку на пустоту/непустоту структуры принято производить не проверкой на равенство пустому/непустому значению, а через логический оператор `not`/его отсутствие. Например, не `if position == None`, а `if not position`.
4. В функции `solve()` в конце хотелось бы возвращать `None`, если решение не существует. 
5. `return` не требует поставновки скобок. Особенно если возвращается всего одна переменная. Там достаточно поставить пробел между `return` и возвращаемым значением.
6. Между функциями принято оставлять 2 пустые строки.

И не забудьте вернуть на место доктесты))

2020-10-30 11:25 UTC, Sofshik commented
Откуда нужно вернуть доктесты? Просто их вроде как изначально не было, только юниттесты :sweat_smile:

2020-10-30 15:47 UTC, anastasiiaCher commented
Вот ваш шаблончик: https://github.com/Dementiy/pybook-assignments/blob/master/homework02/sudoku.py.
То, что в начале функций в тройных кавычках и с тройными стрелочками - доктесты.

2020-10-30 17:34 UTC, Sofshik commented
Как решить ошибку "Unindent does not match any outer indentation level"?

2020-10-30 17:37 UTC, anastasiiaCher commented
Нужно внимательно проверить отступы.

 
С уважением,
Чернышева Анастасия Вадимовна.
>Пятница, 30 октября 2020, 20:34 +03:00 от Sofia Shikalova <notifications@github.com>:
> 
> 
>Как решить ошибку "Unindent does not match any outer indentation level"?
>—
>You are receiving this because your review was requested.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

2020-10-30 21:20 UTC, Dementiy requested changes
Работа без настроенного github actions принята не будет

2020-10-31 17:33 UTC, anastasiiaCher commented
Сделайте репозиторий private.

2020-10-31 17:40 UTC, anastasiiaCher reviewed
Почти все норм, осталось немного поправить.

2020-10-31 17:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return gr
Значение переменной `gr` можно сразу отправить в `return`

2020-10-31 17:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return column
Значение переменной `column` можно сразу отправить в `return`

2020-10-31 17:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return block
Значение переменной `block` можно сразу отправить в `return`

2020-10-31 17:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +                position = (m, l)
`m, l` не нужно заключать в скобки

2020-10-31 17:40 UTC, anastasiiaCher commented on homework02/sudoku.py
> +    return True
Во всей функции `check_solution()` можно не вводить промежуточные переменные

2020-11-01 13:46 UTC, anastasiiaCher commented
Вроде все ок теперь.

2020-11-11 10:41 UTC, merged