Homework06
Sofshik/cs102 pull request #7
Opened 2021-03-26 22:22 UTC by Sofshik

2021-04-05 14:30 UTC, anastasiiaCher requested changes
В принципе все ок. Добавьте небольшой скрипт, демонстрирующий работу вашего классификатора на собранных вами данных, включая вывод точности классификации.

2021-04-20 08:14 UTC, anastasiiaCher requested changes
Очень странная работа алгоритма, ответьте, пожалуйста, на вопрос в комментарии.

2021-04-20 08:14 UTC, anastasiiaCher commented on homework06/classifying.py
> +model.fit(X, y)
Обучение происходит на обучающей выборке, а не на всей, иначе в чем смысл обучения?
Это значит, что в этой строке должно быть `model.fit(X_train, y_train)`. При этом точность классификации получается чуть больше 30% (что в вашей реализации, что в реализации `sklearn`). Возникает вопрос: как проводилась разметка новостей?

2021-04-21 08:30 UTC, Sofshik commented on homework06/classifying.py
> +model.fit(X, y)
Разметка проводилась как и у всех: вручную, долго и мучительно, а под конец к тому же менее старательно и прилежно... Попробую переразметить и проверю результат.

2021-05-13 10:50 UTC, anastasiiaCher commented on homework06/classifying.py
> +model.fit(X, y)
Удалось что-то сделать с повторной разметкой?

2021-05-13 17:24 UTC, Sofshik commented on homework06/classifying.py
> +model.fit(X, y)
Переразметила только часть, не успела проверить результат.
Я видела, что у некоторых работы засчитаны, хотя у них точность примерно как у меня.  Её обязательно нужно повысить?

2021-05-17 13:07 UTC, anastasiiaCher commented on homework06/classifying.py
> +model.fit(X, y)
Протестируйте результат на том, что уже разметили. Важнее поправить аргументы, которые вы передаете в метод `fit()`.

2021-05-18 11:17 UTC, anastasiiaCher approved these changes
Принято.

2021-05-18 11:19 UTC, merged